<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class StudentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('students')->insert([
            [
                'student_id' => '21-0258-471',
                'name' => 'Sheryn Mae Aguado ',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0542-261',
                'name' => 'Eumerson Delos Santos',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0434-713',
                'name' => 'Tiffany Kate Dispo',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0798-660',
                'name' => 'Khyder John Escat',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0715-359',
                'name' => 'Zaki Espaldon',
                'year' => '4th Year',
                'course' => 'BSIT',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0783-230',
                'name' => 'Daniel Ferrer',
                'course' => 'BSCS',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1425-826',
                'name' => 'Jenievy Gamboa',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '22-1000-349',
                'name' => 'Erwin Garcia',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1117-267',
                'name' => 'Maria Angelica Licudan',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0352-140',
                'name' => 'Allen Halog',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0189-243',
                'name' => 'Rasty Malasaga',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1028-949',
                'name' => 'Aaron Malicdem',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1566-344',
                'name' => 'Clarence Mendoza',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0414-237',
                'name' => 'Shaina Nacional',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0325-647',
                'name' => 'Bornio Asley Nuqui',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1374-377',
                'name' => 'Krizel Ocon',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0780-427',
                'name' => 'Mary Jean Pertosa',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1083-214',
                'name' => 'Carla May Quinantoto',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0267-752',
                'name' => 'Connie Ramos',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0201-774',
                'name' => 'Dennis Rodriguez',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1192-460',
                'name' => 'Christian Niel Solis',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1421-779',
                'name' => 'John Reynan Tamayo',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '22-1820-527',
                'name' => 'Norman Jay Tibuli',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0849-329',
                'name' => 'Joey James Ulanday',
                'course' => 'BSIT',
                'year' => '4th Year',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
