<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class StudentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('students')->insert([
            [
                'student_id' => '21-0558-379',
                'name' => 'Rob Lourrenze Kian Abad',
                'course' => 'BSIT',
                'year' => '4th Year',
                'email' => 'abad@cdd.edu.ph',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0530-305',
                'name' => 'Marc Froilan Abaoag',
                'course' => 'BSIT',
                'year' => '4th Year',
                'email' => 'abaoag@cdd.edu.ph',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-1426-782',
                'name' => 'Christine Joy Alcaide',
                'course' => 'BSIT',
                'year' => '4th Year',
                'email' => 'alcaide@cdd.edu.ph',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '21-0182-895',
                'name' => 'Lawrence Justine Alog',
                'course' => 'BSIT',
                'year' => '4th Year',
                'email' => '@cdd.edu.ph',
                'password' => Hash::make('eeram2024'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => '',
            //     'name' => '',
            //     'course' => 'BSIT',
            //     'email' => '@cdd.edu.ph',
            //     'password' => Hash::make('eeram2024'),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
        ]);
    }
}
